### ISSUE TITLE
Linear Search Algorithm (Java) and its time complexity

### ISSUE THREAD

**Issue by Coder2023NewWeloc** [Coder2022New/Searching-Sorting-Algos#2]
Linear Search Algorithm and its time complexity

**Comment by shubham13k** [comment]
Hi I would like to work on it please assign it to me.

**Comment by niteshjeganathan** [comment]
Can you please assign this to me @Coder2022New

**Comment by Coder2023NewWeloc** [comment]
The issue is closed

**Comment by Coder2023NewWeloc** [comment]
The issue is clossed
